#!/usr/bin/env bash
SRC="/Users/luciancooper/Windows/BB/SIM"
YEAR=$1
mkdir "${PWD}/${YEAR}"
cp "${SRC}/CTX/${YEAR}.txt" "${PWD}/${YEAR}/CTX.txt"
cp "${SRC}/EVE/${YEAR}.txt" "${PWD}/${YEAR}/EVE.txt"
cp "${SRC}/GID/${YEAR}.txt" "${PWD}/${YEAR}/GID.txt"
cp "${SRC}/ROS/${YEAR}.txt" "${PWD}/${YEAR}/ROS.txt"
cp "${SRC}/TEAM/${YEAR}.txt" "${PWD}/${YEAR}/TEAM.txt"
echo "Setup Data for ${YEAR}"
