#!/usr/bin/env python

import sys
import progress
import requests
import time
import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy

from bbsim.data import seasonlib


CHUNKSIZE = 1024

def downloadFile(url,tofile):
    r = requests.get(url, stream=True)
    total_size = int(r.headers['content-length'])
    bar = progress.IncrementalBar(10,prefix='Downloading')
    with open(tofile, 'wb') as f:
        for data in r.iter_content(chunk_size = CHUNKSIZE):
            f.write(data)


#def downloadYearData(year,todir):


def single_bar():
    bar = progress.IncrementalBar(30,prefix='Downloading')
    for i in bar:
        time.sleep(0.05)

def multi_bar():
    bar = progress.MultiBar(2,5,'First Level')
    for i in range(len(bar)):
        for x in bar.iter(range(50),'Second Level (%i)'%i):
            time.sleep(0.05)

def main():
    bar = progress.IncrementalBar(prefix='Downloading')
    items = [*range(0,30)]
    bar = progress.IncrementalBar(prefix='Downloading')
    i = bar.iter(items)
    for x in i:
        print(x)
        time.sleep(0.05)
    #print('bbget',file=sys.stderr)
    #data = seasonlib('bbdata.xml')
    #print(f"pids:{len(data[2015].pid)}")
    #print(f"gids:{len(data[2015].gid)}")
    #index = arrpy.SetIndex(data.pid,name=['year','team','pid'])
    #print(f"index:{len(index)}")


if __name__=='__main__':
    main()
