#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy
import numpy as np
import pandas as pd

from bbsim.data import seasonlib
from bbsim.frame import StatFrame
from bbsim.league import LeagueStatSim


def main():
    data = seasonlib('bbdata.xml')
    index = arrpy.SetIndex(data.years,name='year')
    frame = StatFrame(index,LeagueStatSim.data_cols,dtype=LeagueStatSim.data_type)
    sim = LeagueStatSim(frame)
    print('Simulating MLB',file=sys.stderr)
    data.run(sim)
    df = frame.to_dataframe()
    if not sys.stdout.isatty():
        df.to_csv(sys.stdout,index=True)
        return
    print(repr(df))


if __name__=='__main__':
    print('Simulating MLB Stats',file=sys.stderr)
    main()
