#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')

from bbmatrix.core import BBMatrix
from bbsim.data import seasonlib
from bbsim.games import ScoreSim

def main():
    print('Simulating Game Scores',file=sys.stderr)
    data = seasonlib('bbdata.xml')
    matrix = BBMatrix(data.gidIndex,ScoreSim.dcols,dtype=ScoreSim.dtype)
    sim = ScoreSim(matrix)
    data.run(sim)
    if not sys.stdout.isatty():
        matrix.to_csv(sys.stdout)
        return

if __name__=='__main__':
    main()
