#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy
from progress import MultiBar
from bbsim.data import seasonlib
from bbsim.frame import StatFrame
from bbsim.games import ScoreSim


def main():
    print('Simulating Game Scores',file=sys.stderr)
    data = seasonlib('bbdata.xml')
    prog = MultiBar(2,len(data))
    index = arrpy.SetIndex(data.gid,name='gid')
    frame = StatFrame(index,ScoreSim.data_cols,dtype=ScoreSim.data_type)
    sim = ScoreSim(frame)
    for gd in data:
        sim.initYear(gd.year)
        with gd:
            for g in prog.iter(gd,'(%i)'%gd.year):
                sim._simGame(g,gd.gamectx())
    df = frame.to_dataframe()
    df.to_csv(sys.stdout,index=True)

if __name__=='__main__':
    main()
