#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy

from bbsim.data import seasonlib
from bbsim.frame import StatFrame
from bbsim.games import GameStatSim

def main():
    print('Simulating Game Stats',file=sys.stderr)
    data = seasonlib('bbdata.xml')
    index = arrpy.SetIndex(data.gid_team,name=['gid','team'])
    frame = StatFrame(index,GameStatSim.data_cols,dtype=GameStatSim.data_type)
    sim = GameStatSim(frame)
    data.run(sim)
    df = frame.to_dataframe()
    if not sys.stdout.isatty():
        df.to_csv(sys.stdout,index=True)
        return
    

if __name__=='__main__':
    main()
