#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy

from bbsim.data import seasonlib
from bbsim.roster import PIDStatSim

def main():
    data = seasonlib('bbdata.xml')
    sim = PIDStatSim(data.pidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

if __name__=='__main__':
    main()
