#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy
from bbsim.data import seasonlib
from bbsim.frame import StatFrame
from bbsim.roster import PPIDStatSim

def main():
    print('Simulating Game Stats',file=sys.stderr)
    data = seasonlib('bbdata.xml')
    index = arrpy.SetIndex(data.ppid,name=['year','team','pid'])
    frame = StatFrame(index,PPIDStatSim.data_cols,dtype=PPIDStatSim.data_type)
    sim = PPIDStatSim(frame)
    data.run(sim)
    df = frame.to_dataframe()
    if not sys.stdout.isatty():
        df.to_csv(sys.stdout,index=True)
        return

if __name__=='__main__':
    main()
