#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')

from bbsim.data import seasonlib
from bbsim.roster import PPIDStatSim

def main():
    data = seasonlib('bbdata.xml')
    sim = PPIDStatSim(data.ppidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

if __name__=='__main__':
    main()
