#!/usr/bin/env python

import sys
sys.path.append('/Users/luciancooper/projects/pymodule')
import arrpy

from bbmatrix.core import BBMatrix
from bbsim.data import seasonlib
from bbsim.roster import PIDStatSim

def main():
    print('Simulating Game Stats',file=sys.stderr)
    data = seasonlib('bbdata.xml')
    matrix = BBMatrix(data.pidIndex,PIDStatSim.dcols,dtype=PIDStatSim.dtype)
    sim = PIDStatSim(matrix)
    data.run(sim)
    if not sys.stdout.isatty():
        matrix.to_csv(sys.stdout)
        return

if __name__=='__main__':
    main()
