#!/usr/bin/env python

import difflib

def diffCheck(file1,file2):
    with open(file1,'r') as f1,open(file2,'r') as f2:
        for line in difflib.unified_diff(f1.readlines(),f2.readlines(),fromfile=file1,tofile=file2,lineterm='',n=0):
            yield line

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Checks the difference between 2 Files")
    parser.add_argument('file1',help='First file to compare')
    parser.add_argument('file2',help='Second file to compare')
    args = parser.parse_args()
    for l in diffCheck(args.file1,args.file2):
        print(l)
    #print(args)
    #print('File1: ',args.file1)
    #print("File2: ",args.file2)

def parse_range(arg):
    y0,y1 = arg.split('-')
    return range(int(y0),int(y1)+1)

def parse_years(arg):
    return [i for j in [[*parse_range(a)] if ('-' in a) else [int(a)] for a in arg.split(',')] for i in j]
    
def alt():
    import argparse
    parser = argparse.ArgumentParser(description="Baseball Source File Compiler")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-s','--sim',choices=['gid','eve','ros','ctx','team'],help='Compile SIM files')
    group.add_argument('-r','--raw',choices=['ctx','ros','dfn','mod','eve','hnd','ecode'],help='Compile Raw files')
    group.add_argument('--xml',action='store_true',help='Create XML Directory Lookup File')
    #parser.add_argument('type',choices=['gid','eve','ros','ctx','team'],help='File category to compile')
    parser.add_argument('-y','--years',required=True,type=parse_years,help='years to compile')
    #parser.add_argument('-y','--years',required=True,type=parse_years,help='years to compile')
    args = parser.parse_args()
    print(args)


if __name__=='__main__':
    #main()
    alt()
