#!/usr/bin/env python

import sys
import io
sys.path.append('/Users/luciancooper/projects/pymodule')

from bbsim.data import seasonlib
from bbsim.woba import REMSim
from bbsim.league import SeasonStatSim
from bbsim.games import ScoreSim,GameStatSim,RunsPerOutSim,RunsPerPASim
from bbsim.roster import FposOutSim,PIDStatSim,PPIDStatSim


def bb_rpo(data):
    sim = RunsPerOutSim(data.yearIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

def bb_pos(data):
    sim = FposOutSim(data.pidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

def bb_rpa(data):
    sim = RunsPerPASim(data.yearIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

def bb_rem(data):
    sim = REMSim(data.yearIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return


def bbstat_mlb(data):
    sim = SeasonStatSim(data.yearIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

def bbstat_league(data):
    sim = SeasonStatSim(data.leagueIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

# bbstat-mlb
def bgame_score(data):
    sim = ScoreSim(data.gidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

# bgame-stat
def bgame_stat(data):
    sim = GameStatSim(data.gidTeamIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

# bstat-pid
def bstat_pid(data):
    sim = PIDStatSim(data.pidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return

# bstat-ppid
def bstat_ppid(data):
    sim = PPIDStatSim(data.ppidIndex)
    data.run(sim)
    if not sys.stdout.isatty():
        sim.to_csv(sys.stdout)
        return


if __name__=='__main__':
    data = seasonlib('bbdata.xml')
    #bb_rpo(data)
    #bb_pos(data)
    #bb_rpa(data)
    #bb_rem(data)
    #bbstat_mlb(data)
    #bbstat_league(data)
